name: content_resolver
description: A plugin that help app to call ContentResolver on Android.
version: 0.3.1
repository: https://github.com/espresso3389/flutter_content_resolver

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: jp.espresso3389.content_resolver
        pluginClass: ContentResolverPlugin

